### ISSUE TITLE
lab makes easy concept confusing cant figure out to get the errors solved. even the chat people dont know what todo

### ISSUE THREAD

**Issue by sluongo718** [learn-co-curriculum/redux-delete-lab#46]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk
